//
//  PinyinCorpusTests.swift
//  CAppTests
//

import Foundation
import Testing
@testable import CApp

/// Runs the Pinyin golden corpus and reports what it measured.
///
/// The corpus lives in two files next to this one. `pinyin-corpus.tsv` is
/// generated by `tools/generate-pinyin-corpus.py` from CC-CEDICT plus the
/// documented sandhi rules; `pinyin-corpus-manual.tsv` holds the cases whose
/// exceptions are the point and therefore cannot be derived. Neither file
/// takes its expectations from this app's code — that is the whole reason
/// they exist as data rather than as `#expect` lines.
///
/// Two things are measured separately, because they are different claims:
///
/// - **Pronunciation** — the syllables and their tones, compared without
///   spaces. This is what a learner says, and it is the number the benchmark
///   report leads with.
/// - **Spacing** — where the word breaks fall. Orthography, not
///   pronunciation, and it follows the segmentation rather than the lexicon.
///   Reported on its own so a spacing difference cannot be mistaken for a
///   wrong reading.
@MainActor
struct PinyinCorpusTests {

    // MARK: - The corpus

    struct Case {
        let category: String
        let hanzi: String
        /// Empty means: no claim about the text, only about `needsReview`.
        let expected: String
        let needsReview: Bool
        let basis: String
    }

    static let cases: [Case] = load()

    private static func load() -> [Case] {
        ["pinyin-corpus", "pinyin-corpus-manual"].flatMap { name -> [Case] in
            guard let url = Bundle(for: BundleToken.self).url(forResource: name, withExtension: "tsv"),
                  let text = try? String(contentsOf: url, encoding: .utf8) else {
                return []
            }
            return text.split(separator: "\n").compactMap { line -> Case? in
                guard line.hasPrefix("#") == false, line.isEmpty == false else { return nil }
                let fields = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
                guard fields.count >= 5 else { return nil }
                return Case(
                    category: fields[0],
                    hanzi: fields[1],
                    expected: fields[2],
                    needsReview: fields[3] == "true",
                    basis: fields[4]
                )
            }
        }
    }

    /// Only the tones and syllables, so a word break cannot fail a case that
    /// is pronounced correctly.
    private static func pronunciation(_ text: String) -> String {
        text.split(whereSeparator: \.isWhitespace).joined()
    }

    // MARK: - The benchmark

    @Test("The corpus is complete and every case carries its source")
    func corpusIsWellFormed() throws {
        let cases = Self.cases
        #expect(cases.count >= 350, "measured \(cases.count) cases")

        for entry in cases {
            #expect(entry.hanzi.isEmpty == false)
            #expect(entry.basis.isEmpty == false, "\(entry.hanzi) has no stated source")
            // An empty expectation is only allowed where the case is about
            // the review hint. Anywhere else it would be a silent gap.
            if entry.expected.isEmpty {
                #expect(entry.needsReview, "\(entry.hanzi): no expectation and no review claim")
            }
        }

        // Every category the phase asked for is present, with its minimum.
        let minimums = ["A": 50, "B": 30, "C": 30, "D": 30, "E": 20,
                        "F": 40, "G": 30, "H": 30, "J": 20, "K": 4]
        let counts = Dictionary(grouping: cases, by: \.category).mapValues(\.count)
        for (category, minimum) in minimums.sorted(by: { $0.key < $1.key }) {
            let actual = counts[category] ?? 0
            #expect(actual >= minimum, "category \(category): \(actual) of \(minimum) required")
        }
        // Category I is deliberately below the 50 the phase named. The
        // sentences are not missing — 34 of the 60 contain a word the lexicon
        // cannot resolve uniquely, so they are measured in J, where the claim
        // is the review hint rather than a pronunciation. Padding I with
        // sentences chosen for being easy would raise the number and lower
        // what it means.
        #expect((counts["I"] ?? 0) >= 25, "category I: \(counts["I"] ?? 0)")
    }

    @Test("Golden corpus: the app shows the spoken form")
    func goldenCorpus() throws {
        var pronunciationFailures: [(Case, String)] = []
        var spacingFailures: [(Case, String)] = []
        var reviewFailures: [(Case, String)] = []
        var measured = 0

        for entry in Self.cases {
            let resolution = PinyinService.resolution(for: entry.hanzi)

            if resolution.needsReview != entry.needsReview {
                reviewFailures.append((entry, resolution.text))
            }
            guard entry.expected.isEmpty == false else { continue }
            measured += 1

            if Self.pronunciation(resolution.text) != Self.pronunciation(entry.expected) {
                pronunciationFailures.append((entry, resolution.text))
            } else if entry.expected.contains(" "), resolution.text != entry.expected {
                // Spacing is only checked where the corpus states one. Most
                // expectations are written without spaces on purpose — they
                // are derived from the lexicon, which has no word boundaries
                // — so comparing them on spacing would measure the corpus
                // format, not the app. Category K states the boundaries that
                // do matter (A23).
                spacingFailures.append((entry, resolution.text))
            }
        }

        Self.report(
            total: Self.cases.count,
            measured: measured,
            pronunciation: pronunciationFailures,
            spacing: spacingFailures,
            review: reviewFailures
        )

        #expect(measured > 250, "only \(measured) cases carried a pronunciation expectation")

        // Still no threshold on the overall rate — a percentage as a pass
        // mark would quietly turn a measurement into a promise. What is
        // asserted instead is **which** cases fail, by name.
        //
        // Found by the audit, and it was a real hole: this test used to
        // collect the failures, write them to the report and assert
        // nothing. Every one of the 370 cases could have gone wrong while
        // the suite stayed green — and the one mutation that mattered did
        // exactly that. Making `footSplit` always return `nil` flips twelve
        // cases and broke no test, so the 双单格/单双格 distinction, the
        // core of this phase, had no cover at all.
        //
        // Naming the accepted failures works in both directions: a new
        // failure appears, and a fixed one has to be removed here before
        // the suite goes green again.
        let failed = Set(pronunciationFailures.map(\.0.hanzi))
        #expect(
            failed == Self.knownFailures,
            Comment(rawValue: "unexpected: \(failed.subtracting(Self.knownFailures).sorted()), "
                + "no longer failing: \(Self.knownFailures.subtracting(failed).sorted())")
        )
        #expect(reviewFailures.isEmpty, "review flags must match exactly")
        #expect(spacingFailures.isEmpty, "the stated word boundaries must hold")
    }

    /// The cases that are expected to fail, each classified in
    /// `docs/apple-frameworks.md` Q10.
    ///
    /// Every one carries the **linguistically correct** expectation in the
    /// corpus rather than the app's output, so it shows up as a measured
    /// gap instead of disappearing into a word list. Shrinking this set is
    /// progress; growing it silently is not possible.
    static let knownFailures: Set<String> = [
        // `一号` is a date label and keeps its base tone — `一月一号` is
        // `yī yuè yī hào`. Whether a `一` counts or labels is semantic, and
        // the asset dropped CC-CEDICT's glosses, where the classifier
        // marking sits. Class F.
        "一号",
        // CC-CEDICT capitalises `Yi1` inside an ordinary noun, and the
        // proper-noun guard falls for it. Dropping the guard is worse: it
        // would put a wrong `bú` into every `不列颠` compound. Class F.
        "千禧一代",
        // Both `水果` and `果酒` are headwords, so the bracketing is not
        // witnessed and the conservative middle split leaves `水` alone.
        // Class F.
        "水果酒",
        // `看` is ambiguous, so it reaches the rule without a tone and
        // cannot trigger it — `不看` comes out `bù kàn` instead of `búkàn`.
        // The review hint is set, and correctly so, but the pronunciation is
        // still wrong: `看` here is the `kàn` of "not watch", so the learner
        // form is determined. Class F.
        //
        // This case was briefly moved out of the measured set on the grounds
        // that expecting a pronunciation *and* a review hint is
        // contradictory. It is not — it is the most informative combination,
        // "unsure and wrong" — and moving it out applied a different standard
        // than the three cases above. Put back after the review.
        "不看",
    ]

    /// The classes that have to work, whatever the overall rate says.
    ///
    /// A high average must not hide a broken rule, so these are asserted one
    /// by one instead of being folded into a percentage.
    @Test("Critical rule classes", arguments: [
        ("苹果", "píngguǒ"), ("谢谢", "xièxie"), ("早上", "zǎoshang"),
        ("朋友", "péngyou"), ("妈妈", "māma"), ("明白", "míngbai"),
        ("买东西", "mǎi dōngxi"), ("东西南北", "dōngxī nánběi"),
        ("你好", "níhǎo"), ("水果", "shuíguǒ"), ("展览馆", "zhánlánguǎn"),
        ("不对", "búduì"), ("不好", "bùhǎo"), ("对不起", "duìbuqǐ"),
        ("一天", "yìtiān"), ("一年", "yìnián"), ("一点", "yìdiǎn"),
        ("一下", "yíxià"), ("一定", "yídìng"),
        // The accuracy pass's highest-priority case, and by far the most
        // common: `一个`. Belongs in the list that exists so a good average
        // cannot hide a broken rule.
        ("一个", "yíge"), ("一个人", "yígèrén"),
        ("银行", "yínháng"), ("行为", "xíngwéi"), ("长大", "zhǎngdà"),
        // The 单双格 side of the third-tone rule, which is what `footSplit`
        // and the second cycle exist for. Without these the whole
        // distinction could be removed and only the corpus would notice —
        // and until the audit, not even that.
        ("小老鼠", "xiǎoláoshǔ"), ("纸老虎", "zhǐláohǔ"),
        ("小酒馆", "xiǎojiúguǎn"), ("养老保险", "yánglǎo báoxiǎn"),
        ("哪里哪里", "nálǐ nálǐ"),
    ])
    func criticalClasses(hanzi: String, expected: String) {
        let resolution = PinyinService.resolution(for: hanzi)
        #expect(
            Self.pronunciation(resolution.text) == Self.pronunciation(expected),
            "\(hanzi): got \(resolution.text), expected \(expected)"
        )
        #expect(resolution.needsReview == false, "\(hanzi) should not need review")
    }

    // MARK: - Report

    /// Writes the benchmark report where the phase gate can read it.
    ///
    /// A file rather than `print`: `xcodebuild` does not reliably surface test
    /// stdout, and a report nobody can read is not a report.
    private static func report(
        total: Int,
        measured: Int,
        pronunciation: [(Case, String)],
        spacing: [(Case, String)],
        review: [(Case, String)]
    ) {
        let exact = measured - pronunciation.count
        let percent = measured > 0 ? Double(exact) / Double(measured) * 100 : 0

        var lines = [
            "Pinyin Accuracy Benchmark",
            "",
            "Cases: \(total)",
            "With a pronunciation expectation: \(measured)",
            "Exact learner-pronunciation match: \(exact) / \(measured)",
            String(format: "%.1f %%", percent),
            "",
            "Spacing differences (pronounced correctly): \(spacing.count)",
            "Review-flag mismatches: \(review.count)",
            "",
            "By category:",
        ]

        let byCategory = Dictionary(grouping: pronunciation, by: \.0.category).mapValues(\.count)
        let counts = Dictionary(grouping: cases, by: \.category).mapValues(\.count)
        for category in counts.keys.sorted() {
            let failed = byCategory[category] ?? 0
            let all = counts[category] ?? 0
            lines.append("  \(category): \(all - failed) / \(all)")
        }

        if pronunciation.isEmpty == false {
            lines.append("")
            lines.append("Pronunciation failures:")
            for (entry, got) in pronunciation {
                lines.append("  [\(entry.category)] \(entry.hanzi): got '\(got)', expected '\(entry.expected)'")
                lines.append("      basis: \(entry.basis)")
            }
        }
        if spacing.isEmpty == false {
            lines.append("")
            lines.append("Spacing differences:")
            for (entry, got) in spacing {
                lines.append("  [\(entry.category)] \(entry.hanzi): got '\(got)', expected '\(entry.expected)'")
            }
        }
        if review.isEmpty == false {
            lines.append("")
            lines.append("Review-flag mismatches:")
            for (entry, got) in review {
                let wanted = entry.needsReview ? "review" : "no review"
                lines.append("  [\(entry.category)] \(entry.hanzi): wanted \(wanted), text '\(got)'")
            }
        }

        let text = lines.joined(separator: "\n") + "\n"
        // Next to the source rather than in the simulator's sandbox: the
        // temporary directory of a test bundle lives inside a container that
        // is thrown away, and a report nobody can find is not a report.
        // `#filePath` resolves at compile time, so this works on any machine
        // without a hard-coded path. `.reports/` is git-ignored.
        let directory = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent(".reports")
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try? text.write(
            to: directory.appendingPathComponent("pinyin-benchmark.txt"),
            atomically: true,
            encoding: .utf8
        )
    }
}

/// Only there to locate the test bundle for the corpus files.
private final class BundleToken {}
